repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-go
        args: [ "markdown", "table", "--output-file", "README.md", "./terraform/" ]
      - id: terraform-docs-go
        args: [ "markdown", "table", "--output-file", "README.md", "./modules/ckxng_oci_network/" ]
      - id: terraform-docs-go
        args: [ "markdown", "table", "--output-file", "README.md", "./modules/ckxng_oci_compute/" ]
      - id: terraform-docs-go
        args: [ "markdown", "table", "--output-file", "README.md", "./modules/ckxng_aws_basic_compute/" ]
      - id: terraform-docs-go
        args: [ "markdown", "table", "--output-file", "README.md", "./modules/ckxng_az_network/" ]
      - id: terraform-docs-go
        args: [ "markdown", "table", "--output-file", "README.md", "./modules/ckxng_az_basic_compute/" ]
