tenancy_ocid="ocid1.tenancy.oc1..aaaaaaaa...2ca3kmna"
compartment_ocid="ocid1.tenancy.oc1..aaaaaaaa...2ca3kmna"
subnet_ocid="ocid1.subnet.oc1.phx.aaaaaaaa...eh65rfhq"
user_ocid="ocid1.user.oc1..aaaaaaaa...t4omojtq"
key_fingerprint="5c:b6:...:ad:e4"
private_key="SENSITIVE"
ssh_authorized_keys="ssh-rsa AAAAB3Nz...9ruWvw== keyname"